#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/buildroot-gcc342/bin/mipsel-linux-gcc -DZLIB_SHARED -DZLIB  -DOPENSSL_THREADS -D_REENTRANT -DHAVE_DLFCN_H -DL_ENDIAN -DTERMIO -Os -mips2 -mno-branch-likely -G 0 -fno-builtin -DCPU=MIPS32 -DMIPSEL -DNO_STRINGS_H -DOPENSSL_NO_HW"
  #define PLATFORM "RT2880"
  #define DATE "Wed Jul  2 09:34:19 KST 2014"
#endif
