#!/bin/sh
#       $1      the interface name used by pppd (e.g. ppp3)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd
#

PPP_OPMODE=`nvram_get 2860 wan_ppp_opmode`
if [ "$PPP_OPMODE" = "" -o "$PPP_OPMODE" = "KeepAlive" ]; then
	exit 0
fi

echo "ip-pre-up:do_something"

if [ "$2" = "/dev/ttyS0" -o "$2" = "/dev/ttyS1" ]; then
    exit 0
fi

if [ -f /var/run/$1_status ]; then rm /var/run/$1_status; fi

PPP_IFACE=$1

ifconfig $PPP_IFACE up
iptables -t nat -A POSTROUTING -o $PPP_IFACE -j MASQUERADE --random
route add default dev $PPP_IFACE metric 3

module route refresh

