#!/bin/sh
#       $1      the interface name used by pppd (e.g. ppp3)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd

if [ "$2" = "/dev/ttyS0" -o "$2" = "/dev/ttyS1" ]; then
    exit 0
fi

echo "ip-down:do somting."

rm -f /etc_ro/resolv.conf

